### ISSUE TITLE
Create branches and fork them

### ISSUE THREAD

**Issue by NancheungTest** [Nancheung23/JavaSpringboot-PT1#1]
## Description
Learning how to fork, and set up multiple branches. One for each member of a team (4 branches), and the main one. Fix the merging process.

## Steps
- Open main brach
- Create a new one, with your own username
- Commit something
- Clone main branch
- Merge them and fix possible merging issues

## Acceptance criteria
- Each team member created a new branch for themselves
- Each team member has committed a change to the main branch
- Make a screenshot of done branches and upload it to teams
- Link here

## Outcome
[Branches](https://tuni.sharepoint.com/:i:/r/sites/TG-TTHarjoittelut2024-x-team-16/Shared%20Documents/x-team-16/Project%20documentation%20-%20kanban%20board/[Branches.png](https://tuni.sharepoint.com/:i:/r/sites/TG-TTHarjoittelut2024-x-team-16/Shared%20Documents/x-team-16/Project%20documentation%20-%20kanban%20board/Branches.png?csf=1&web=1&e=pFWE5k)?csf=1&web=1&e=pFWE5k)

**Comment by AlicjaKo** [comment]
We have solved the multiple branch issue, and merging it with main
